### PR TITLE
Update CHANGELOG.md (stdlib)

### PR DESCRIPTION
**Pull request by radrow**

### CODE REVIEW

**Comment by hanssv** [comment]
I covered List comprehensions in the CHANGELOG already in #130, and maybe let's skip StdLib until @UlfNorell has worked his magic there?

**Comment by radrow** [comment]
@hanssv What kind of magic are we speaking about?

**Comment by UlfNorell** [comment]
We were discussing getting rid of the implicit import and making `flat_map` for desugared list comprehensions a builtin. Also possibly precomputing the result of parsing the standard library modules to make it a bit faster.

**Comment by radrow** [comment]
Is there an issue for this?

**Pull request closed without merging**
