### PR TITLE
Lima master merge

### PR DESCRIPTION
**Pull request by radrow**
don't squash

### CODE REVIEW

**Review by hanssv — APPROVED** [review]
Always hard to review these backmerges, but I assume it has been tried with the Aeternity node repo?

**Review by gorbak25 — APPROVED** [review]

**Review by gorbak25 — CHANGES_REQUESTED** [review]
CT suite fails in ae node

**Comment by hanssv** [comment]
What is the issue?

**Comment by radrow** [comment]
`<<bad argument>>`, investigating the problem

**Review by gorbak25 — APPROVED** [review]

**Pull request merged**
